### ISSUE TITLE
tap tap tap. is this thing on ?

### ISSUE THREAD

**Issue by PinkMushroom** [soupi/haskell-sdl2gl#1]
so instead of creating the sandbox i just installed necessary packages and tried cabal build.

i get this :

src/MySDL/MySDL.hs:19:88:
    ‘SDL.windowSize’ is not a record selector
    In the expression:
      SDL.defaultWindow
        {SDL.windowOpenGL = Just (C.glConf config),
         SDL.windowSize = C.size config}
    In an equation for ‘myWindowConfig’:
        myWindowConfig config
          = SDL.defaultWindow
              {SDL.windowOpenGL = Just (C.glConf config),
               SDL.windowSize = C.size config}

**Comment by soupi** [comment]
Hi,

Apparently in the package sdl2 the record field windowSize has changed to windowInitialSize as seen [here](https://github.com/haskell-game/sdl2/commit/342ec10106bf618e5faa3aa34738c4b20ee8f70a).

Thanks for noticing! I hope  [this commit](https://github.com/soupi/haskell-sdl2gl/commit/2c05e022369ee54b232b4584e73ad46483a60c4f) fixes the issue.

**Comment by PinkMushroom** [comment]
cabal: At least the following dependencies are missing:
sdl2 >=2.0.0

i'm confused is this referring to the C-library sdl2 or the cabal library sdl2 ?
i'm assuming the c-library, but since i have 2.0.3 installed, i'm not sure how i'm getting that message..

and i see this too:

rejecting: sdl2-1.3.1/installed-494... (conflict: sdl2gl => sdl2>=2.0.0)

**Comment by soupi** [comment]
Hi,

The requirement `sdl2 >= 2.0.0` refers to the new sdl2 Haskell library API which is currently only available on github ([link](https://github.com/haskell-game/sdl2)), and may even change before it's release.

Currently, you can only find up to version `1.3.1` of the sdl2 Haskell library on Hackage [here](http://hackage.haskell.org/package/sdl2).

In order to use the new API and not the one on Hackage you must clone the repo and use add-source for cabal to recognize it, as shown in the README.

Hope this helps.

**Comment by PinkMushroom** [comment]
doh! ok- i got confused. for some reason i thought the hackage version and the git version were the same (probably because hackage version had been updated relatively recently).  let me do this right and see what happens.
thanks for your help!
my goal for this weekend is to write sdl2 with haskell :-)

**Comment by soupi** [comment]
You welcome and good luck.

**Comment by PinkMushroom** [comment]
success! thanks again.
